using UnityEngine;


namespace Peg
{
    /// <summary>
    /// This class is meant for simple visual confirmation of Hash values generated by Unity's Animator.
    /// </summary>
    public class HashedStringValue : MonoBehaviour
    {
        public HashedString Value;
    }
}
